apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: stagedkubernetesnetworkpolicies.crd.projectcalico.org
spec:
  scope: Namespaced
  group: crd.projectcalico.org
  version: v1
  names:
    kind: StagedKubernetesNetworkPolicy
    plural: stagedkubernetesnetworkpolicies
    singular: stagedkubernetesnetworkpolicy
