apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: stagedglobalnetworkpolicies.crd.projectcalico.org
spec:
  scope: Cluster
  group: crd.projectcalico.org
  version: v1
  names:
    kind: StagedGlobalNetworkPolicy
    plural: stagedglobalnetworkpolicies
    singular: stagedglobalnetworkpolicy
