apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: stagednetworkpolicies.crd.projectcalico.org
spec:
  scope: Namespaced
  group: crd.projectcalico.org
  version: v1
  names:
    kind: StagedNetworkPolicy
    plural: stagednetworkpolicies
    singular: stagednetworkpolicy
