# permissions for end users to view apiservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apiserver-viewer-role
rules:
- apiGroups:
  - operator.tigera.io
  resources:
  - apiservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.tigera.io
  resources:
  - apiservers/status
  verbs:
  - get
