# permissions for end users to edit demoresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: demoresource-editor-role
rules:
- apiGroups:
  - operator.tigera.io
  resources:
  - demoresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.tigera.io
  resources:
  - demoresources/status
  verbs:
  - get
