# permissions for end users to view logcollectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logcollector-viewer-role
rules:
- apiGroups:
  - operator.tigera.io
  resources:
  - logcollectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.tigera.io
  resources:
  - logcollectors/status
  verbs:
  - get
