# permissions for end users to view managementclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managementcluster-viewer-role
rules:
- apiGroups:
  - operator.tigera.io
  resources:
  - managementclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.tigera.io
  resources:
  - managementclusters/status
  verbs:
  - get
