# permissions for end users to edit managementclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managementcluster-editor-role
rules:
- apiGroups:
  - operator.tigera.io
  resources:
  - managementclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.tigera.io
  resources:
  - managementclusters/status
  verbs:
  - get
