# permissions for end users to view managementclusterconnections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managementclusterconnection-viewer-role
rules:
- apiGroups:
  - operator.tigera.io
  resources:
  - managementclusterconnections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.tigera.io
  resources:
  - managementclusterconnections/status
  verbs:
  - get
