# permissions for end users to edit tigerastatuses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tigerastatus-editor-role
rules:
- apiGroups:
  - operator.tigera.io
  resources:
  - tigerastatuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.tigera.io
  resources:
  - tigerastatuses/status
  verbs:
  - get
