blank_issues_enabled: false
contact_links:
  - name: Report a bug or request a feature
    url: https://github.com/projectcalico/calico/issues/new/choose
    about: The operator is developed in the projectcalico/calico repository. Please file here.
  - name: Ask a question
    url: https://slack.projectcalico.org
    about: Questions and discussion with the Calico community on Slack.
