apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  componentResources:
    - componentName: Node
      resourceRequirements:
        requests:
          memory: 64Mi
          cpu: 250m
        limits:
          memory: 500Mi
          cpu: 500m
    - componentName: Typha
      resourceRequirements:
        requests:
          memory: 64Mi
          cpu: 250m
    - componentName: KubeControllers
      resourceRequirements:
        limits:
          memory: 500Mi
          cpu: 500m
