apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: intrusiondetections.operator.tigera.io
spec:
  group: operator.tigera.io
  names:
    kind: IntrusionDetection
    listKind: IntrusionDetectionList
    plural: intrusiondetections
    singular: intrusiondetection
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: IntrusionDetection installs the components required for Tigera
        intrusion detection. At most one instance of this resource is supported. It
        must be named "tigera-secure".
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Specification of the desired state for Tigera intrusion detection.
          type: object
        status:
          description: Most recently observed state for Tigera intrusion detection.
          properties:
            state:
              description: State provides user-readable status.
              type: string
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
