// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	bastapi "github.com/tigera/operator/pkg/bastapi"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// GetOrganization provides a mock function with given fields: organizationID
func (_m *Client) GetOrganization(organizationID string) (*bastapi.Organization, error) {
	ret := _m.Called(organizationID)

	var r0 *bastapi.Organization
	if rf, ok := ret.Get(0).(func(string) *bastapi.Organization); ok {
		r0 = rf(organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bastapi.Organization)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(organizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClient(t mockConstructorTestingTNewClient) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
