# Components defined here are required to be kept in sync with hack/gen-versions/calico.go.tpl
title: release-v3.32
components:
  libcalico-go:
    version: release-v3.32
  typha:
    version: release-v3.32
  node:
    version: release-v3.32
  cni:
    version: release-v3.32
  node-windows:
    version: release-v3.32
  cni-windows:
    version: release-v3.32
  kube-controllers:
    version: release-v3.32
  goldmane:
    version: release-v3.32
  flexvol:
    version: release-v3.32
  apiserver:
    version: release-v3.32
  csi:
    version: release-v3.32
  csi-node-driver-registrar:
    version: release-v3.32
  key-cert-provisioner:
    version: release-v3.32
  whisker:
    version: release-v3.32
  whisker-backend:
    version: release-v3.32
  envoy-gateway:
    version: release-v3.32
  envoy-proxy:
    version: release-v3.32
  envoy-ratelimit:
    version: release-v3.32
  guardian:
    version: release-v3.32
  istio-pilot:
    version: release-v3.32
  istio-install-cni:
    version: release-v3.32
  istio-ztunnel:
    version: release-v3.32
  istio-proxyv2:
    version: release-v3.32
  webhooks:
    version: release-v3.32
