# Components defined here are required to be kept in sync with hack/gen-versions/calico.go.tpl
title: release-v3.33
components:
  libcalico-go:
    version: release-v3.33
  typha:
    version: release-v3.33
  node:
    version: release-v3.33
  cni:
    version: release-v3.33
  node-windows:
    version: release-v3.33
  cni-windows:
    version: release-v3.33
  third-party-cni-plugins:
    version: release-v3.33
  kube-controllers:
    version: release-v3.33
  goldmane:
    version: release-v3.33
  flexvol:
    version: release-v3.33
  apiserver:
    version: release-v3.33
  csi:
    version: release-v3.33
  key-cert-provisioner:
    version: release-v3.33
  whisker:
    version: release-v3.33
  whisker-backend:
    version: release-v3.33
  envoy-gateway:
    version: release-v3.33
  envoy-proxy:
    version: release-v3.33
  envoy-ratelimit:
    version: release-v3.33
  guardian:
    version: release-v3.33
  istio-pilot:
    version: release-v3.33
  istio-install-cni:
    version: release-v3.33
  istio-ztunnel:
    version: release-v3.33
  istio-proxyv2:
    version: release-v3.33
  webhooks:
    version: release-v3.33
  calico:
    version: release-v3.33
