components:
  cnx-manager:
    image: tigera/cnx-manager
    version: v2.7.6
  voltron:
    image: tigera/voltron
    version: v2.7.6
  cnx-apiserver:
    image: tigera/cnx-apiserver
    version: v2.7.6
  cnx-queryserver:
    image: tigera/cnx-queryserver
    version: v2.7.6
  cnx-kube-controllers:
    image: tigera/kube-controllers
    version: v2.7.6
  typha:
    image: tigera/typha
    version: v2.7.6
  cnx-node:
    image: tigera/cnx-node
    version: v2.7.6
  fluentd:
    image: tigera/fluentd
    version: v2.7.6
  es-proxy:
    image: tigera/es-proxy
    version: v2.7.6
  eck-kibana:
    version: 7.3.2
  kibana:
    image: tigera/kibana
    version: v2.7.6
  elasticsearch-operator:
    registry: docker.elastic.co
    image: eck/eck-operator
    version: 0.9.0
  eck-elasticsearch:
    version: 7.3.2
  elasticsearch:
    image: tigera/elasticsearch
    version: v2.7.6
  elastic-tsee-installer:
    image: tigera/intrusion-detection-job-installer
    version: v2.7.6
  es-curator:
    image: tigera/es-curator
    version: v2.7.6
  intrusion-detection-controller:
    image: tigera/intrusion-detection-controller
    version: v2.7.6
  compliance-controller:
    image: tigera/compliance-controller
    version: v2.7.6
  compliance-reporter:
    image: tigera/compliance-reporter
    version: v2.7.6
  compliance-snapshotter:
    image: tigera/compliance-snapshotter
    version: v2.7.6
  compliance-server:
    image: tigera/compliance-server
    version: v2.7.6
  compliance-benchmarker:
    image: tigera/compliance-benchmarker
    version: v2.7.6
  guardian:
    image: tigera/guardian
    version: v2.7.6
  # Below components are all maintained by 3rd parties and thus specify a 'registry' to indicate
  # to the docs & manifest tooling not to default to the tigera registry.
