components:
  typha:
    version: v3.12.2
  calico/node:
    version: v3.12.2
  calico/cni:
    version: release-v3.12
  calico/kube-controllers:
    version: v3.12.2
  flexvol:
    version: release-v3.12
