# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/operator.tigera.io_apiservers.yaml
- bases/operator.tigera.io_applicationlayers.yaml
- bases/operator.tigera.io_authentications.yaml
- bases/operator.tigera.io_compliances.yaml
- bases/operator.tigera.io_egressgateways.yaml
- bases/operator.tigera.io_imagesets.yaml
- bases/operator.tigera.io_installations.yaml
- bases/operator.tigera.io_intrusiondetections.yaml
- bases/operator.tigera.io_logcollectors.yaml
- bases/operator.tigera.io_logstorages.yaml
- bases/operator.tigera.io_managementclusterconnections.yaml
- bases/operator.tigera.io_managementclusters.yaml
- bases/operator.tigera.io_managers.yaml
- bases/operator.tigera.io_monitors.yaml
- bases/operator.tigera.io_nonclusterhosts.yaml
- bases/operator.tigera.io_packetcaptureapis.yaml
- bases/operator.tigera.io_policyrecommendations.yaml
- bases/operator.tigera.io_tenants.yaml
- bases/operator.tigera.io_tigerastatuses.yaml
- bases/operator.tigera.io_tlspassthroughroutes.yaml
- bases/operator.tigera.io_tlsterminatedroutes.yaml

- bases/operator.tigera.io_demoresources.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_foos.yaml
#- path: patches/cainjection_in_demoresources.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.

#configurations:
#- kustomizeconfig.yaml
