// Copyright (c) 2023 Tigera, Inc. All rights reserved.

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package utils

import operatorv1 "github.com/tigera/operator/api/v1"

// tweakILMPoliciesForCloud tweaks the ILM policies generated by listILMPolicies()
// for Calico Cloud.
// It updates the [majorPctOfTotalDisk] to include runtime logs.
// [majorPctOfTotalDisk] takes up 70% of ES disk space.
// Currently, 85% of the 70% is used for flow logs.
// This will instead:
//   - Allocate 68.5% of the 70% ES disk space to flow logs.
//   - Allocate 16.5% of the 70% ES disk space to runtime logs.
func (es *esClient) tweakILMPoliciesForCloud(ls *operatorv1.LogStorage, policies map[string]policyDetail) {
	totalEsStorage := getTotalEsDisk(ls)
	majorPctOfTotalDisk := 0.7

	policies["tigera_secure_ee_flows"] = buildILMPolicy(totalEsStorage, majorPctOfTotalDisk, 0.685, int(*ls.Spec.Retention.Flows))
	policies["tigera_secure_ee_runtime"] = buildILMPolicy(totalEsStorage, majorPctOfTotalDisk, 0.165, 8)
}
