#!/bin/bash
#
# This script updates a bundle generated by `operator-sdk generate bundle` so
# that we can certify it.
#
# This script should be not be run directly. See the bundle target in the
# Makefile.
set -eu

# VERSION is the version of the operator to publish.
if [[ -z "${VERSION}" ]]; then
	echo VERSION is undefined - run with vars VERSION=X.Y.Z PREV_VERSION=D.E.F
	exit 1
fi

# OPERATOR_IMAGE_INSPECT is the base64-encoded output from "docker image inspect quay.io/tigera/operator:v${VERSION}"
if [[ -z "${OPERATOR_IMAGE_INSPECT}" ]]; then
	echo OPERATOR_IMAGE_INSPECT is undefined
	exit 1
fi

# PREV_VERSION is the version of the operator that VERSION replaces. If this version does not replace a version, use 0.0.0
if [[ -z "${PREV_VERSION}" ]]; then
	echo PREV_VERSION is undefined - run with vars VERSION=X.Y.Z PREV_VERSION=D.E.F
	exit 1
fi

OPERATOR_IMAGE_INSPECT=$(echo $OPERATOR_IMAGE_INSPECT | base64 -d)
OPERATOR_IMAGE_DIGEST=$(echo $OPERATOR_IMAGE_INSPECT | jq -r '.[0].RepoDigests[] | select(. | contains("quay.io/tigera/operator"))')
OPERATOR_MANIFEST_INSPECT=$(echo $OPERATOR_MANIFEST_INSPECT | base64 -d )

CSV=bundle/${VERSION}/manifests/tigera-operator.clusterserviceversion.yaml

# Rearrange the bundle layout.
rm -rf bundle/${VERSION}
mkdir bundle/${VERSION}
mv bundle/{metadata,manifests} bundle/${VERSION}

YAML_UPDATE_FILE=yaml-updates
rm -f ${YAML_UPDATE_FILE}

# Update the CSV. Set the operator image container image and creation timestamp annotations.
#
TIMESTAMP=$(echo ${OPERATOR_IMAGE_INSPECT} | jq -r .[0].Created)
cat <<- EOF >> ${YAML_UPDATE_FILE}
	.metadata.annotations.containerImage = "${OPERATOR_IMAGE_DIGEST}" |
	.metadata.annotations.createdAt = "${TIMESTAMP}" |
EOF

# Add the features annotations per https://docs.openshift.com/container-platform/4.14/operators/operator_sdk/osdk-generating-csvs.html
FEATURES=features.operators.openshift.io
cat <<- EOF >> ${YAML_UPDATE_FILE}
	.metadata.annotations."${FEATURES}/disconnected" = "false" |
	.metadata.annotations."${FEATURES}/fips-compliant" = "false" |
	.metadata.annotations."${FEATURES}/proxy-aware" = "false" |
	.metadata.annotations."${FEATURES}/tls-profiles" = "false" |
	.metadata.annotations."${FEATURES}/token-auth-aws" = "false" |
	.metadata.annotations."${FEATURES}/token-auth-azure" = "false" |
	.metadata.annotations."${FEATURES}/token-auth-gcp" = "false" |
	.metadata.annotations."${FEATURES}/cnf" = "false" |
	.metadata.annotations."${FEATURES}/cni" = "true" |
	.metadata.annotations."${FEATURES}/csi" = "false" |
EOF

# Set the operator container image by digest in the tigera-operator deployment spec embedded in the CSV.
cat <<- EOF >> ${YAML_UPDATE_FILE}
	.spec.install.spec.deployments[0].spec.template.spec.containers[0].image = "${OPERATOR_IMAGE_DIGEST}" |
	.spec.install.spec.deployments[0].spec.template.spec.containers[0].name = "tigera-operator" |
	.spec.install.spec.deployments[0].spec.selector.matchLabels.name = "tigera-operator" |
EOF

# Set the previous version of the operator that this version replaces.
if [[ "${PREV_VERSION}" != "0.0.0" ]]; then
    cat <<- EOF >> ${YAML_UPDATE_FILE}
		.spec.replaces = "tigera-operator.v${PREV_VERSION}" |
	EOF
fi

# Add labels for each supported architecture in the CSV file, in the
# metadata.labels section:
# e.g. operatorframework.io/arch.arm64: supported
# At least amd64 is needed so that we can use the SHA256 of the manifest image rather
# than the specific SHA of the amd64 image.
for arch in $(echo "$OPERATOR_MANIFEST_INSPECT" | jq -r '.manifests[].platform.architecture'); do
    cat <<- EOF >> ${YAML_UPDATE_FILE}
		.metadata.labels."operatorframework.io/arch.${arch}" = "supported" |
	EOF
done

# Set the CSV to ignore previous versions when updating. Use brackets to preserve the
# dot in the key "olm.skipRange".
cat <<- EOF >> ${YAML_UPDATE_FILE}
	.metadata.annotations."olm.skipRange" = "<${VERSION}" |
EOF

# Add required 'relatedImages' to CSV
# E.g.
#
#   relatedImages:
#     - name: tigera-operator
#       image: quay.io/tigera/operator@sha256:b4e3eeccfd3d5a931c07f31c244b272e058ccabd2d8155ccc3ff52ed78855e69
cat <<- EOF >> ${YAML_UPDATE_FILE}
	.spec.relatedImages[0].name = "tigera-operator" |
	.spec.relatedImages[0].image = "${OPERATOR_IMAGE_DIGEST}" |
EOF

# This line ends our yq script and commits the update
cat <<- EOF >> ${YAML_UPDATE_FILE}
	.
EOF

yq -i --from-file "${YAML_UPDATE_FILE}" "${CSV}"

# exit 1

# Now start updates to the bundle dockerfile. First update the package name.
sed -i 's/\(operators\.operatorframework\.\io\.bundle\.package\.v1\)=operator/\1=tigera-operator/' bundle.Dockerfile

# Supported OpenShift versions. Specify min version.
openshiftVersions=v4.16-v4.18

# Add in required labels
cat <<EOF >> bundle.Dockerfile
LABEL com.redhat.openshift.versions="${openshiftVersions}"
LABEL com.redhat.delivery.backport=true
LABEL com.redhat.delivery.operator.bundle=true
EOF

# Remove unneeded labels
sed -i -e 's/.*operators\.operatorframework\.io\.metrics.*//' \
       -e 's/.*operators\.operatorframework\.io\.test\.config\.v1.*//' \
       -e 's/.*operators\.operatorframework\.io\.test\.mediatype\.v1.*//' bundle.Dockerfile

# Fix the bundle path
sed -i -E '/^COPY bundle\/(manifests|metadata)/d' bundle.Dockerfile

cat <<EOF >> bundle.Dockerfile
COPY ${VERSION}/manifests /manifests/
COPY ${VERSION}/metadata /metadata/
EOF

# Delete empty permissions (we only set clusterPermissions) otherwise the CSV
# validation fails
yq -i 'del(.spec.install.spec.permissions)' "${CSV}"

# Remove unneeded empty lines
sed -i '/^$/d' bundle.Dockerfile

# Lastly move the dockerfile to the bundle dir, renaming it with the version
mv bundle.Dockerfile bundle/bundle-v${VERSION}.Dockerfile

#
# Update annotations file. Update package name.
#
sed -i 's/\(operators\.operatorframework\.io\.bundle\.package\.v1\): operator/\1: tigera-operator/' bundle/${VERSION}/metadata/annotations.yaml

# Remove unneeded labels
sed -i 's/.*operators\.operatorframework\.io\.metrics.*//' bundle/${VERSION}/metadata/annotations.yaml
sed -i 's/.*operators\.operatorframework\.io\.test.*//' bundle/${VERSION}/metadata/annotations.yaml

# Remove unneeded empty lines
sed -i '/^$/d' bundle/${VERSION}/metadata/annotations.yaml

# Add required com.redhat.openshift.versions
cat <<EOF >> bundle/${VERSION}/metadata/annotations.yaml
  com.redhat.openshift.versions: ${openshiftVersions}
EOF
